### ISSUE TITLE
Snap to Roads, large dataset crashes with ERR_CONNECTION_ABORTED

### ISSUE THREAD

**Issue by westlakem** [googlemaps/google-maps-services-js#148]
I have a function that takes GPS data and maps it.  When I have few datapoints (less than 200), I can wrap the code into 2 service calls and I get a valid response.  When I plug in a trip we did that has almost 3000 datapoints (30 service calls), It crashes.

The error message from the browser console:
```
zone.js:1022 GET https://roads.googleapis.com/v1/snapToRoads?path=[REMOVED TO SAVE SPACE]&key=[MY_API_KEY]
 net::ERR_CONNECTION_CLOSED
(anonymous) @ zone.js:1022
ClientRequest._onFinish @ request.js:148
(anonymous) @ request.js:61
EventEmitter.emit @ events.js:78
finishMaybe @ _stream_writable.js:607
endWritable @ _stream_writable.js:615
Writable.end @ _stream_writable.js:571
ClientRequest.end @ request.js:292
makeUrlRequest @ make-url-request.js:106
(anonymous) @ make-api-call.js:114
Task.start @ task.js:84
(anonymous) @ make-api-call.js:113
(anonymous) @ task.js:238
Item.run @ browser.js:153
drainQueue @ browser.js:123
ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:4724
ZoneDelegate.invokeTask @ zone.js:420
Zone.runTask @ zone.js:188
ZoneTask.invokeTask @ zone.js:496
ZoneTask.invoke @ zone.js:485
timer @ zone.js:2025
setTimeout (async)
scheduleTask @ zone.js:2046
ZoneDelegate.scheduleTask @ zone.js:407
onScheduleTask @ zone.js:297
ZoneDelegate.scheduleTask @ zone.js:401
Zone.scheduleTask @ zone.js:232
Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1092
(anonymous) @ zone.js:2061
proto.(anonymous function) @ zone.js:1372
runTimeout @ browser.js:41
process.nextTick @ browser.js:143
(anonymous) @ task.js:227
setListener @ task.js:114
... 
[SHORTENED]
...
core.js:1440 ERROR Error: Uncaught (in promise): TypeError: Failed to fetch
TypeError: Failed to fetch
    at resolvePromise (zone.js:809)
    at eval (zone.js:728)
    at callback (make-api-call.js:153)
    at eval (make-api-call.js:146)
    at eval (task.js:247)
    at Item.run (browser.js:153)
    at drainQueue (browser.js:123)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4724)
    at ZoneDelegate.invokeTask (zone.js:420)
```

Error in Debug Console:

```
Error: Uncaught (in promise): TypeError: Failed to fetch
message:"Uncaught (in promise): TypeError: Failed to fetch\nTypeError: Failed to fetch"
promise:ZoneAwarePromise {__zone_symbol__state: 0, __zone_symbol__value: TypeError: Failed to fetch}
rejection:TypeError: Failed to fetch
stack:"Error: Uncaught (in promise): TypeError: Failed to fetch\nTypeError: Failed to fetch\n    at resolvePromise (webpack-internal:///../../../../zone.js/dist/zone.js:809:31)\n    at eval (webpack-internal:///../../../../zone.js/dist/zone.js:728:17)\n    at callback (webpack-internal:///../../../../@google/maps/lib/internal/make-api-call.js:153:13)\n    at eval (webpack-internal:///../../../../@google/maps/lib/internal/make-api-call.js:146:29)\n    at eval (webpack-internal:///../../../../@google/maps/lib/internal/task.js:247:27)\n    at Item.run (webpack-internal:///../../../../process/browser.js:153:14)\n    at drainQueue (webpack-internal:///../../../../process/browser.js:123:42)\n    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:421:31)\n    at Object.onInvokeTask (webpack-internal:///../../../core/esm5/core.js:4939:33)\n    at ZoneDelegate.invokeTask (webpack-internal:///../../../../zone.js/dist/zone.js:420:36)"
task:ZoneTask {_zone: Zone, runCount: 0, _zoneDelegates: null, …}
zone:Zone {_properties: Object, _parent: Zone, _name: "angular", …}
__proto__:Object {constructor: , name: "Error", message: "", …}
```

My service code is as follows:
```
import { Injectable } from '@angular/core';
import { GpsData } from './gps-data'
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/fromPromise';
import 'rxjs/add/operator/map'
import 'rxjs/add/observable/concat';

declare function require(path: string): any;
var googleMapsClient = require('@google/maps').createClient({
  key: 'MY_API_KEY',
  Promise: Promise
});


@Injectable()
export class GoogleMapsService {

  constructor() { }
  tracePathOnRoad(csv: Array<GpsData>) {
    let path = []
    let promises = []
    csv.forEach((element: GpsData) => {
      path.push([element.Latitude, element.Longitude])
    });
    let buckets = this.assembleBuckets(path)
    buckets.forEach(bucket => {
      promises.push(Observable.fromPromise(googleMapsClient.snapToRoads({
        path: path,
        interpolate: false
      }).asPromise()).map(response => {console.log('Retrieved Response'); console.log(response); return response}))
    });
    return Observable.concat.apply(this, promises);
  }

  assembleBuckets(csv) {
    let buckets = [];
    let csvCopy = JSON.parse(JSON.stringify(csv));
    while (csvCopy.length > 0) {
      buckets.push(csvCopy.splice(0, 99));
    }
    return buckets
  }
```

and my component calls it like so: 

```

  ngOnInit() {
    this.getSnappedRoute()
  }

  getSnappedRoute() {
    let inputCSV = this.fordInputDataService.getCSV()
    this.googleMapsService.tracePathOnRoad(inputCSV).subscribe(routeLocations => {
      this.snappedRoute = routeLocations['json']['snappedPoints'];
      this.openMap();
      let snappedRouteLocations = this.getLatAndLongFromSnappedRoutes();
      this.drawRouteOnMap(snappedRouteLocations);
    })
  };

Any help is appreciated.

**Comment by westlakem** [comment]
I found the errors of my way.... In my service I was passing the entire path instead of the bucket of 99 points.
