### ISSUE TITLE
 InvalidValueError: unexpected property "travelMode"

### ISSUE THREAD

**Issue by SachaG** [googlemaps/google-maps-services-js#195]
I'm getting the following error when I try to make a request while specifying the `travelMode` option:

```
(node:65354) UnhandledPromiseRejectionWarning: InvalidValueError: unexpected property "travelMode"
at /Users/sacha/Dev/zensroom/node_modules/@google/maps/lib/internal/validate.js:90:15
at /Users/sacha/Dev/zensroom/node_modules/@google/maps/lib/internal/validate.js:159:15
at Array.forEach (<anonymous>)
at Object.validator (/Users/sacha/Dev/zensroom/node_modules/@google/maps/lib/internal/validate.js:158:16)
at Object.distanceMatrix (/Users/sacha/Dev/zensroom/node_modules/@google/maps/lib/index.js:55:25)
```

Looking at [the code](https://github.com/googlemaps/google-maps-services-js/blob/d94576873a238bf5bdd81eec983a7aa24eabdba4/lib/apis/distance-matrix.js#L49-L51), it seems like the proper options is not:

```
travelMode: 'WALKING'
```

As specified [in the docs](https://developers.google.com/maps/documentation/javascript/examples/distance-matrix), but instead:

```
mode: 'walking'
```

This should probably be documented/corrected somewhere?

**Comment by SachaG** [comment]
Oh ok, my bad! That's pretty confusing though, also the documentation doesn't make it very easy to locate the right API docs.
