### ISSUE TITLE
findPlace() thrown fields error with "plus_code"

### ISSUE THREAD

**Issue by taichunmin** [googlemaps/google-maps-services-js#252]
as title.

```
InvalidValueError: in property "fields": at index 7: not one of "formatted_address", "geometry", "icon", "id", "name", "permanently_closed", "photos", "place_id", "scope", "types", "vicinity", "opening_hours", "price_level", "rating"
    at Function.InvalidValueError.prepend (/Users/taichunmin/git/google-map-place-id-nodejs/node_modules/@google/maps/lib/internal/validate.js:30:12)
    at /Users/taichunmin/git/google-map-place-id-nodejs/node_modules/@google/maps/lib/internal/validate.js:77:35
    at /Users/taichunmin/git/google-map-place-id-nodejs/node_modules/@google/maps/lib/internal/validate.js:168:15
    at Array.forEach (<anonymous>)
    at Object.validator (/Users/taichunmin/git/google-map-place-id-nodejs/node_modules/@google/maps/lib/internal/validate.js:167:16)
    at Object.findPlace (/Users/taichunmin/git/google-map-place-id-nodejs/node_modules/@google/maps/lib/index.js:55:25)
    at module.exports (/Users/taichunmin/git/google-map-place-id-nodejs/youbike.js:6:32)
    at repl:1:50 {
  message: 'in property "fields": at index 7: not one of "formatted_address", ' +
    '"geometry", "icon", "id", "name", "permanently_closed", "photos", ' +
    '"place_id", "scope", "types", "vicinity", "opening_hours", ' +
    '"price_level", "rating"',
  name: 'InvalidValueError'
}
```

**Comment by amuramoto** [comment]
Fixed in https://github.com/googlemaps/google-maps-services-js/pull/256

Thanks for reporting!
