### ISSUE TITLE
uuid dependency in v1.1 and before causing node 6 and below to crash

### ISSUE THREAD

**Issue by regevbr** [googlemaps/google-maps-services-js#348]
#### Steps to reproduce

  1. install fresh copy of @google/maps dependency (1.1 or previous version) in node 6 or below
  2. Use the library as usual.

#### Stack trace
```
/node_modules/@google/maps/node_modules/uuid/v4.js:8
);
^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules/@google/maps/lib/util.js:100:42)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/@google/maps/lib/index.js:122:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> 
...

Process finished with exit code 1

```

The reason for this issue is the semver requirement in package.json for the uuid library is not restrictive enought:
```
"uuid": ">=2.2.1"
```
And because of that, version 7 of the uuid library is used which is not compatible with node 6 and below...

I see that you have "released" v2 which doesn't have the uuid depndency but that version is not in npm yet...

**Comment by jpoehnelt** [comment]
Node 6 is beyond end of life, [2019-04-30](https://github.com/nodejs/Release#end-of-life-releases). The new version of this library has been published to [@googlemaps/google-maps-services-js](https://www.npmjs.com/package/@googlemaps/google-maps-services-js).
