### ISSUE TITLE
Geocoder: Client does not accept axios config

### ISSUE THREAD

**Issue by stebl** [googlemaps/google-maps-services-js#361]
#### Environment details

1. macOS Catalina version 10.15.3
2. @googlemaps/google-maps-services-js version 2.3.0
3. node v12.16.1

#### Steps to reproduce

1. Create a new project
2. Install google map services
3. Run the code snippet

#### Code example

```javascript
const Client = require("@googlemaps/google-maps-services-js").Client;

const client = new Client({
  config: {
    timeout: 500
  }
})

client.geocode({
  params: {
    address: 'San Francisco, CA',
    key: 'yourKeyHere'
  }
})
.catch(reason => console.log(reason))
```

Alternatively, you can even fully specify the axios config the client provides in the defaultAxiosClient and it will produce the same results. 

```javascript
const Client = require("@googlemaps/google-maps-services-js").Client;
const HttpsAgent = require("agentkeepalive").HttpsAgent

const version = 'test'
const defaultHttpsAgent = new HttpsAgent({ keepAlive: true });
const defaultTimeout = 10000;
const userAgent = `google-maps-services-node-${version}`;
const X_GOOG_MAPS_EXPERIENCE_ID = "X-GOOG-MAPS-EXPERIENCE-ID";

const defaultConfig = {
  timeout: defaultTimeout,
  httpsAgent: defaultHttpsAgent,
  headers: { "User-Agent": userAgent }
};

const client = new Client({
  config: defaultConfig
})

client.geocode({
  params: {
    address: 'San Francisco, CA',
    key: 'yourKeyHere'
  }
})
.catch(reason => console.log(reason))
```

#### Stack trace
```
TypeError [ERR_INVALID_ARG_TYPE]: The "options.agent" property must be one of Agent-like Object, undefined, or false. Received an insta
nce of Object
    at new ClientRequest (_http_client.js:133:11)
    at Object.request (https.js:314:10)
    at RedirectableRequest._performRequest (/Users/stebl/Documents/google-maps/node_modules/follow-redirects/index.js:169:24)
    at new RedirectableRequest (/Users/stebl/Documents/google-maps/node_modules/follow-redirects/index.js:66:8)
    at Object.wrappedProtocol.request (/Users/stebl/Documents/google-maps/node_modules/follow-redirects/index.js:307:14)
    at dispatchHttpRequest (/Users/stebl/Documents/google-maps/node_modules/axios/lib/adapters/http.js:179:25)
    at new Promise (<anonymous>)
    at httpAdapter (/Users/stebl/Documents/google-maps/node_modules/axios/lib/adapters/http.js:21:10)
    at dispatchRequest (/Users/stebl/Documents/google-maps/node_modules/axios/lib/core/dispatchRequest.js:52:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

####

You can workaround this issue by instead creating the `axiosInstance` yourself; although, this is not ideal.  

```
const axiosAgent = axios.create(defaultConfig)

return new Client({
  axiosInstance: axiosAgent
})
```

**Comment by jpoehnelt** [comment]
closed via #362 

Let me know if you have any further issues. Confirmed it was working with https://github.com/jpoehnelt/google-maps-services-js-demo/commit/6a20ce6ba394feb11cc8a187d2b7af48ba022798 too.

-----------

:tada: This PR is included in version 2.3.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@googlemaps/google-maps-services-js/v/2.3.1)
- [GitHub release](https://github.com/googlemaps/google-maps-services-js/releases/tag/v2.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
