### ISSUE TITLE
Jest: TypeError: Cannot read property 'best_guess' of undefined

### ISSUE THREAD

**Issue by soullivaneuh** [googlemaps/google-maps-services-js#521]
#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ..."): Directions
2. OS type and version: Manjaro Linux
3. Library version and other environment information: v3.1.13 with typescript@3.9.7

#### Steps to reproduce

1. Create a mock of google-maps-services-js
2. Write a sample test calling the direction API

Notes:

1. The logic works correctly if I test it manually using ts-node.
2. Replacing the enum value by it's string representation (`traffic_model: 'best_guess'`) make tests working, but of course, Typescript is unhappy.

#### Code example

Here is the google-maps service mock:

```typescript
import {
  Client as BaseClient, DirectionsRequest, DirectionsResponse, DirectionsRoute, Status,
} from '@googlemaps/google-maps-services-js';

const makeDirectionsRoute = (legDistanceValues: number[]): DirectionsRoute => ({
  summary: '',
  legs: legDistanceValues.map((legDistanceValue) => ({
    distance: {
      value: legDistanceValue,
      text: '',
    },
    duration: {
      value: 0,
      text: '',
    },
    duration_in_traffic: {
      // Approaches a realistic value according to the distance.
      value: legDistanceValue / 240 * 60,
      text: '',
    },
    departure_time: {
      value: new Date(),
      text: '',
      time_zone: '',
    },
    arrival_time: {
      value: new Date(),
      text: '',
      time_zone: '',
    },
    start_address: '',
    start_location: {
      lat: 0,
      lng: 0,
    },
    end_address: '',
    end_location: {
      lat: 0,
      lng: 0,
    },
    steps: [],
  })),
  waypoint_order: [],
  overview_polyline: { points: '' },
  bounds: {
    northeast: {
      lat: 0,
      lng: 0,
    },
    southwest: {
      lat: 0,
      lng: 0,
    },
  },
  copyrights: '',
  warnings: [],
  fare: {
    currency: '',
    value: 0,
    text: '',
  },
  overview_path: [],
});
export class Client extends BaseClient {
  // eslint-disable-next-line class-methods-use-this
  directions(request: DirectionsRequest): Promise<DirectionsResponse> {
    return new Promise((resolve) => resolve({
      status: 0,
      statusText: '',
      headers: null,
      config: {},
      data: {
        status: Status.OK,
        error_message: '',
        geocoded_waypoints: [],
        routes: [
          makeDirectionsRoute([3000, 750, 250]),
          // The following one should be selected. (2km)
          makeDirectionsRoute([1000, 750, 250]),
          makeDirectionsRoute([10000, 750, 250]),
        ],
        available_travel_modes: [],
      },
    }));
  }
}

export default null;
```

The function that use the service:

```typescript
import { Client, TrafficModel } from '@googlemaps/google-maps-services-js';
import { chunk } from 'lodash';

const key = process.env.GOOGLE_API_KEY || '';
const client = new Client({});

interface DistanceResult {
  kilometers: number;
  minutes: number;
}

const getDistanceMatrix = (addresses: string[], departure_time: Date): Promise<DistanceResult> => client
  .directions({
    params: {
      key,
      origin: addresses[0],
      destination: addresses[addresses.length - 1],
      waypoints: addresses.slice(1, -1),
      traffic_model: TrafficModel.best_guess,
      departure_time,
      // Important! Necessary to calculate the shortest route.
      alternatives: true,
    },
  })
  .then((directions) => directions.data.routes
    .map(
      (route): DistanceResult => ({
        kilometers: route.legs.reduce((km, leg) => km + leg.distance.value / 1000, 0),
        minutes: route.legs.reduce((mins, leg) => mins + leg.duration_in_traffic.value / 60, 0),
      }),
    )
    .sort(
      (distanceA, distanceB): number => distanceA.kilometers - distanceB.kilometers,
    )[0]);

export const getDistance = (addresses: string[], departure_time: Date): Promise<DistanceResult> => {
  let oldChunk: string[];

  return Promise.all(
    // @see https://developers.google.com/maps/documentation/distance-matrix/usage-and-billing
    chunk(addresses, 9).map((currentChunk) => {
      const matrixData = [
        // In case of multiple chunk, we have to get the distance
        // from the last address of the previous chunk to the first address of the current one.
        ...oldChunk ? [oldChunk[oldChunk.length - 1]] : [],
        ...currentChunk,
      ];
      oldChunk = currentChunk;
      // TODO: Departure time should be the arrival time of the last chunk.
      return getDistanceMatrix(matrixData, departure_time);
    }),
  ).then((distances) => distances.reduce((d1, d2) => ({
    kilometers: d1.kilometers + d2.kilometers,
    minutes: d1.minutes + d2.minutes,
  })));
};

export default null;
```

The related Jest test:

```typescript
import { getDistance } from '../src/google-maps';

describe('distance calculation', () => {
  it(
    'picks the shortest route',
    // Address contents are not needed, the response is always the same provided by the mocked service.
    // @see __mocks__/@googlemaps/google-maps-services-js.ts
    () => getDistance(['', ''], new Date()).then((distance) => {
      expect(distance.kilometers).toBe(2);
      expect(distance.minutes).toBe(42);
    }),
  );
});
```

#### Stack trace

```
 FAIL  test/google-maps.test.ts
  ● distance calculation › picks the shortest route

    TypeError: Cannot read property 'best_guess' of undefined



      at getDistanceMatrix (src/google-maps.ts:622:61)
      at src/google-maps.ts:688:12
          at Array.map (<anonymous>)
      at Object.<anonymous>.exports.getDistance (src/google-maps.ts:669:32)
      at Object.<anonymous> (test/google-maps.test.ts:8:11)
```

**Comment by jpoehnelt** [comment]
https://github.com/googlemaps/google-maps-services-js/blob/50c89a103f78fa1b7a9b909631b4346b56974ae5/src/directions.ts#L124

the traffic_model field is optional.

**Comment by soullivaneuh** [comment]
@jpoehnelt You misunderstood the issue here, the fact the field is optional is not a problem.

To be clear, this works:

```typescript
traffic_model: 'best_guess'
```

This does not works (but should):

```typescript
traffic_model: TrafficModel.best_guess
```

The error:

```
