### ISSUE TITLE
Distance matrix origin/destination params error

### ISSUE THREAD

**Issue by JonathanGetahun** [googlemaps/google-maps-services-js#563]
Running node 12.16,
Getting TypeError: o.map is not a function when attempting to add lat/lng into origin/destination parameters. 

When I switched to an array error became TypeError: Cannot use 'in' operator to search for 'lat' in 38.8809629.

Unsure if this is something from my end, I can't seem to figure out the format to inputting lat&lng coordinates for origin/destination. I've tried making it an object to no avail.

First attempt
    latitude = 38.8809629,
    longitude = 77.0283309

    params:{
        origins:latitude,longitude,
        destinations:[lat,lng],
        key:process.env.GOOGLE_MAPS_API_KEY,
    }

TypeError: o.map is not a function
    at Object.origins (/Users/jonathangetahun/Documents/ATM-4-ME/node_modules/@googlemaps/google-maps-services-js/dist/distance.js:34:21)
    at /Users/jonathangetahun/Documents/ATM-4-ME/node_modules/@googlemaps/google-maps-services-js/dist/serialize.js:108:52
    at Array.forEach (<anonymous>)
    at /Users/jonathangetahun/Documents/ATM-4-ME/node_modules/@googlemaps/google-maps-services-js/dist/serialize.js:106:29
    at buildURL (/Users/jonathangetahun/Documents/ATM-4-ME/node_modules/axios/lib/helpers/buildURL.js:30:24)
    at dispatchHttpRequest (/Users/jonathangetahun/Documents/ATM-4-ME/node_modules/axios/lib/adapters/http.js:109:13)
    at new Promise (<anonymous>)
    at Object.httpAdapter [as adapter] (/Users/jonathangetahun/Documents/ATM-4-ME/node_modules/axios/lib/adapters/http.js:46:10)
    at /Users/jonathangetahun/Documents/ATM-4-ME/node_modules/@googlemaps/google-maps-services-js/dist/adapter.js:55:10
    at new Promise (<anonymous>) {
  config: {
    raxConfig: {
      currentRetryAttempt: 0,
      retry: 3,
      retryDelay: 100,
      instance: [Function],
      backoffType: 'exponential',
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      statusCodesToRetry: [Array]
    }
  }
}

Second attempt:

    params:{
        origins:[latitude,longitude],
        destinations:[lat,lng],
        key:process.env.GOOGLE_MAPS_API_KEY,
    }

TypeError: Cannot use 'in' operator to search for 'lat' in 38.8809629
    at latLngToString (/Users/jonathangetahun/Documents/ATM-4-ME/node_modules/@googlemaps/google-maps-services-js/dist/serialize.js:29:20)
    at Array.map (<anonymous>)
    at Object.origins (/Users/jonathangetahun/Documents/ATM-4-ME/node_modules/@googlemaps/google-maps-services-js/dist/distance.js:34:21)
    at /Users/jonathangetahun/Documents/ATM-4-ME/node_modules/@googlemaps/google-maps-services-js/dist/serialize.js:108:52
    at Array.forEach (<anonymous>)
    at /Users/jonathangetahun/Documents/ATM-4-ME/node_modules/@googlemaps/google-maps-services-js/dist/serialize.js:106:29
    at buildURL (/Users/jonathangetahun/Documents/ATM-4-ME/node_modules/axios/lib/helpers/buildURL.js:30:24)
    at dispatchHttpRequest (/Users/jonathangetahun/Documents/ATM-4-ME/node_modules/axios/lib/adapters/http.js:109:13)
    at new Promise (<anonymous>)
    at Object.httpAdapter [as adapter] (/Users/jonathangetahun/Documents/ATM-4-ME/node_modules/axios/lib/adapters/http.js:46:10) {
  config: {
    raxConfig: {
      currentRetryAttempt: 0,
      retry: 3,
      retryDelay: 100,
      instance: [Function],
      backoffType: 'exponential',
      httpMethodsToRetry: [Array],
      noResponseRetries: 2,
      statusCodesToRetry: [Array]
    }
  }
}

**Comment by JonathanGetahun** [comment]
Went ahead and used this format: [{lat:response[0],lng:response[1]}]
