### ISSUE TITLE
InvalidValueError('missing property "' + key + '"');

### ISSUE THREAD

**Issue by gpavel** [googlemaps/google-maps-services-js#70]
```javascript
class Places {
    constructor (key) {
        this.client = require('@google/maps').createClient({ key });
    }

    getDetails (placeId) {
        return this.client.place({ placeId }).asPromise();
    }
}

const places = new Places(API_KEY);
places.getDetails('ChIJj0YI_QPj20ARuhrB8tXzHAo')
    .then(console.log)
    .catch(console.error);
```

```
throw new InvalidValueError('missing property "' + key + '"');
          ^
Error
    at new InvalidValueError (/home/gureev_cr/repos/matchplayer-backend/node_modules/@google/maps/lib/internal/validate.js:23:17)
    at Object.validator (/home/gureev_cr/repos/matchplayer-backend/node_modules/@google/maps/lib/internal/validate.js:83:17)
    at Object.place (/home/gureev_cr/repos/matchplayer-backend/node_modules/@google/maps/lib/index.js:51:25)
    at Places.getDetails (/home/gureev_cr/repos/matchplayer-backend/server/services/Places.js:48:28)
    at Object.<anonymous> (/home/gureev_cr/repos/matchplayer-backend/server/services/Places.js:54:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Process finished with exit code 1
```

**Comment by shivanagesh** [comment]
Hey @gpavel 

There mistake in your code, you forgot mentioned for key for place id

The correct code:

class Places {
    constructor (key) {
        this.client = require('@google/maps').createClient({ key });
    }

    getDetails (placeId) {
        return this.client.place({  placeid: placeId }).asPromise();
    }
}

const places = new Places(API_KEY);
places.getDetails('ChIJj0YI_QPj20ARuhrB8tXzHAo')
    .then(console.log)
    .catch(console.error); 

This should work

**Comment by pawarvijay** [comment]
```
googleMapsClient.place({
		placeid: 'ChIJzTXekTbB5zsRxRfqh-f4Rb8',
		language: 'fr',
		fields: ['name', 'rating', 'formatted_phone_number', 'geometry'],
	},
	(err, response) => {
		if (!err) {
			console.log(response.json);
		}
	}
);
```
