### ISSUE TITLE
AxiosError thrown when Internet Connection Offline

### ISSUE THREAD

**Issue by mrjackyliang** [googlemaps/google-maps-services-js#951]
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ** 

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response. 

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/). 

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

Please be sure to include as much information as possible:

#### Environment details

1. Geocode API
2. macOS Ventura 13.1
3. @googlemaps/google-maps-services-js@3.3.27

#### Steps to reproduce

  1. Take internet connection offline
  2. Try running any request

#### Code example

```js
try {
    const api = await client.reverseGeocode({
      params: {
        language: Language.en,
        latlng: {
          latitude,
          longitude,
        },
        result_type: [AddressType.street_address],
        key: 'invalid or valid API key, doesn't matter here',
      },
    });
}
```

#### Stack trace
```
AxiosError: options must be an object
    at Object.assertOptions (/xxx/node_modules/axios/dist/node/axios.cjs:3675:11)
    at Axios.request (/xxx/node_modules/axios/dist/node/axios.cjs:3750:17)
    at Function.wrap [as request] (/xxx/node_modules/axios/dist/node/axios.cjs:29:15)
    at /xxx/node_modules/retry-axios/dist/index.js:1:1819
    at async fetchGoogleGeocode (webpack-internal:///(api)/./src/external-api/google-geocode.ts:26:21) {
  code: 'ERR_BAD_OPTION_VALUE'
}
```

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react with :+1: so we can see what is popular when we triage.
--------

@mrjackyliang Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._
